# Generated by Django 5.0.3 on 2024-06-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follows'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follows',
            unique_together={('follower', 'followed')},
        ),
    ]
