# Generated by Django 5.0.3 on 2024-09-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
